# version: '3.8'

# services:
#   database:
#     image: mongo
#     container_name: mongodb
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongodb_data:/data/db
#     # networks:
#     # - shared

#   server:
#     build: ./server
#     container_name: python_server
#     network_mode: service:database
#     # depends_on:
#     #   - database

# volumes:
#   mongodb_data:
#    driver: local

# # networks:
# #   shared:
# #     driver: bridge



version: '3.8'

services:
  database:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  server:
    build: ./server
    container_name: python_server
    network_mode: service:database
    depends_on:
      - database

volumes:
  mongodb_data:
    driver: local
