version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - mongodb_network

  python_server:
    build: ./server
    container_name: python_server
    ports:
      - "5000:5000"
    networks:
      - mongodb_network
    depends_on:
      - mongodb

  react_client:
    build: ./client
    container_name: react_client
    ports:
      - "3000:3000"
    networks:
      - mongodb_network

networks:
  mongodb_network:
    driver: bridge
